name: testcompose


on: 
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run dockercompose
        run: |
         docker compose up
      - name: Test with pytest
        run: |
          pytest